Repository hmcts/civil-sdt, pull requests merged in 2023-05, with the labels that each got.

#147 Fix build issues in main branch
  charts/civil-sdt/Chart.yaml
  charts/civil-sdt/values.yaml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-147

#151 Temporarily suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-151

#156 Add SDT key vault
  infrastructure/key-vault.tf
  infrastructure/main.tf
Labels: ns:civil, prd:civil, add-or-update, rel:civil-sdt-pr-156

#152 Add database setup to infrastructure code
  charts/civil-sdt/Chart.yaml
  charts/civil-sdt/values.preview.template.yaml
  charts/civil-sdt/values.yaml
  infrastructure/.terraform-version
  infrastructure/database.tf
  infrastructure/key-vault.tf
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/service-bus.tf
  infrastructure/state.tf
Labels: ns:civil, prd:civil, destroy, rel:civil-sdt-pr-152

#162 Configure project to use Application Insights v3
  .gitignore
  Dockerfile
  build.gradle
  charts/civil-sdt/Chart.yaml
  charts/civil-sdt/values.preview.template.yaml
  charts/civil-sdt/values.yaml
  infrastructure/app-insights.tf
  lib/applicationinsights.json
  src/main/resources/application.yaml
Labels: ns:civil, prd:civil, add-or-update, rel:civil-sdt-pr-162

#163 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-163

#164 Fix application insights error
  Dockerfile
  lib/applicationinsights.json
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-164

#165 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-165

#168 Update servicebus chart version
  charts/civil-sdt/Chart.yaml
  charts/civil-sdt/values.preview.template.yaml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-168
