Repository hmcts/civil-sdt, pull requests merged in 2023-09, with the labels that each got.

#207 Temporarily suppressed CVE-2023-41080
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-207

#220 Fix CVE-2023-41080
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-220

#247 Temporarily suppress jetty CVEs
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-247

#242 Manage app insights with renovate
  Dockerfile
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-242

#269 SDT-166: SDT common version updated to 1.1.0
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-269

#281 SDT-165 - Deleted dependabot config file
  .github/dependabot.yml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-281
