Repository hmcts/civil-sdt, pull requests merged in 2023-10, with the labels that each got.

#266 Tidy up build.gradle
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-266

#304 Temporarily suppress CVE-2023-4586
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-304

#308 Replace deprecated BeanMembersShouldSerialize PMD rule
  config/pmd/ruleset.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-308

#311 Temporarily suppress CVE-2023-36414 and CVE-2023-36415
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-311

#205 SDT-158: Only query CMC if ready for alt service
  services/src/main/java/uk/gov/moj/sdt/services/SubmitQueryService.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/SubmitQueryServiceTest.java
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-205

#320 SDT-157: SDT: Upgrade Postgres database to v15
  build.gradle
  config/owasp/suppressions.xml
  docker/database/Dockerfile
  infrastructure/aat.tfvars
  infrastructure/database.tf
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/variables.tf
  services/src/integ-test/java/uk/gov/moj/sdt/services/messaging/IndividualRequestMdbIntTest.java
  services/src/integ-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterIntAsbTest.java
  services/src/integ-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterIntTest.java
  services/src/main/java/uk/gov/moj/sdt/services/TargetApplicationSubmissionService.java
  services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
  services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/TargetApplicationSubmissionServiceTest.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/utils/MessagingUtilityTest.java
Labels: ns:civil, prd:civil, add-or-update, rel:civil-sdt-pr-320

#322 SDT-177: Remove redundant suppressions
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-322

#323 SDT-157: point to v15 DB
  charts/civil-sdt/Chart.yaml
  charts/civil-sdt/values.preview.template.yaml
  charts/civil-sdt/values.yaml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-323

#326 Temporarily suppressed CVE-2023-4586
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-326
