Repository hmcts/civil-sdt, pull requests merged in 2024-02, with the labels that each got.

#433 Update export script
  scripts/legacy-db-migration/export/export_bulk_submissions.sql
  scripts/legacy-db-migration/export/export_error_logs.sql
  scripts/legacy-db-migration/export/export_individual_requests.sql
  scripts/legacy-db-migration/validation/data_migration_validation_oracle.sql
Labels: ns:civil, prd:civil, no-changes, rel:civil-sdt-pr-433

#416 Remove Terraform azuread provider
  infrastructure/state.tf
Labels: ns:civil, prd:civil, no-changes, rel:civil-sdt-pr-416

#465 Remove log4j-to-slf4j exclusions from civil-sdt build.gradle
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-465
