Repository hmcts/civil-sdt, pull requests merged in 2024-01, with the labels that each got.

#425 DTSPO-15909 - migrated Application Insights
  infrastructure/app-insights.tf
Labels: ns:civil, prd:civil, add-or-update, rel:civil-sdt-pr-425

#434 Remove suppression for CVE-2023-4586
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-434

#438 SDT-184
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-438

#443 SDT-185
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-443

#449 SDT-186: Updated log4j dependencies and sdtCommonVersion to 2.1.0
  build.gradle
Labels: ns:civil, prd:civil, no-changes, rel:civil-sdt-pr-449
