Repository hmcts/civil-sdt, pull requests merged in 2024-06, with the labels that each got.

#546 SDT-218
  build.gradle
Labels: ns:civil, prd:civil, aat/no-changes, prod/no-changes, rel:civil-sdt-pr-546

#557 SDT-208: Key vault access for AM dashboard pipeline
  infrastructure/key-vault.tf
Labels: ns:civil, prd:civil, aat/add-or-update, prod/add-or-update, rel:civil-sdt-pr-557

#544 SDT-215: Corrected bulk submission completed code
  services/src/integ-test/java/uk/gov/moj/sdt/services/UpdateRequestServiceIntTest.java
  services/src/integ-test/resources/uk/gov/moj/sdt/services/sql/UpdateRequestServiceIntTest.sql
  services/src/main/java/uk/gov/moj/sdt/services/AbstractSdtService.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/UpdateRequestServiceTest.java
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-544

#563 CVE-2024-35255 suppression
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-563

#556 SDT-219: Added count method to Individual Request Dao
  build.gradle
  dao/src/integ-test/java/uk/gov/moj/sdt/dao/IndividualRequestDaoTest.java
  dao/src/integ-test/resources/uk/gov/moj/sdt/dao/sql/IndividualRequestDaoTest.sql
  dao/src/main/java/uk/gov/moj/sdt/dao/IndividualRequestDao.java
  services/src/main/java/uk/gov/moj/sdt/services/RequeueOldIndividualRequests.java
  services/src/unit-test/java/uk/gov/moj/sdt/services/RequeueOldIndividualRequestsTest.java
Labels: ns:civil, prd:civil, aat/no-changes, rel:civil-sdt-pr-556, prod/destroy

#564 Add debug logging
  dao/src/main/java/uk/gov/moj/sdt/dao/GenericDao.java
  services/src/main/java/uk/gov/moj/sdt/services/AbstractSdtService.java
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-564

#568 Remove pricing tier from TF
  infrastructure/service-bus.tf
Labels: aat/destroy, prod/destroy
