Repository hmcts/civil-sdt, pull requests merged in 2025-06, with the labels that each got.

#703 SDT-246: Update sdt-common version
  build.gradle
Labels: ns:civil, prd:civil, aat/add-or-update, prod/add-or-update, rel:civil-sdt-pr-703

#738 SDT-249: Migrate to Azure Artifacts
  build.gradle
  settings.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-738

#754 Added CVE-2024-38808 to suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-754

#756 Revert 3 renovate changes that caused the build to fail
  build.gradle
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-756

#759 Suppress CVE 2023 1932
  config/owasp/suppressions.xml
Labels: ns:civil, prd:civil, rel:civil-sdt-pr-759

#753 SDT-256 Enable reporting on DB infrastructure for AMDB.
  infrastructure/database.tf
Labels: ns:civil, prd:civil, aat/no-changes, prod/add-or-update, rel:civil-sdt-pr-753
